#!/bin/bash
#
# Simple check show error password authorization
#
# Usage: check_beanstalk [-H] [-w] [-c] [-t]
#   -H --help       output this help
#   -w --warn       warning treshold messages in queue authorization
#   -c --crit       critical treshold messages in queue authorization
#   -t --time       time (min) to read log
#   -l --log        path to log authorization
#
# Default setting (warn=50, crit=70, time=20, log=/var/log/secure)
# WARNING: execution time increases from the specified time
# Copyleft TolkIT (team@tolkit.top)
# Author Aleksey Maltsev (lexa.thinker@gmail.com)

# Default Settings
state=3
current_time=$(date +%s)
states_text=("ok" "warning" "critical" "unknown")
warn=${warn:=50}
crit=${crit:=70}
period=${period:=1200}    # minutes in seconds
log_file=${log_file:="/var/log/secure"}

declare -A OS
OS["centos"]="/var/log/secure"
OS["ubuntu"]="/var/log/auth.log"
OS["debian"]="/var/log/auth.log"
# Your OS could be here

# Search distribution name OS and add path to log
for name in ${!OS[@]}; do
    if [ "$( < /etc/os-release grep -w "ID" | grep -c "${name}")" -eq 1 ]; then
        log_file=${OS[$name]}
        check_support_os=$name
    else
        check_support_os=$( < /etc/os-release grep -w "ID" | awk '{print substr($0, 4, length($0)-1)}' | sed 's/"//g')
    fi
done

# Check add key
while [[ -n "$1" ]]; do
    case $1 in
        --warn | -w)
            warn=$2
            shift
            ;;
        --crit | -c)
            crit=$2
            shift
            ;;
        --time | -t)
            (( period = $2 * 60 ))
            shift
            ;;
        --log | -l)
            log_file=$2
            shift
            ;;

        --help | -H)
            sed -n "2,15p" "$0" | tr -d '#'
            exit 3
            ;;
        *)
            echo "Unknown argument: $1"
            exit 3
            ;;
    esac
    shift
done

# Check exist file
if [ ! -e $log_file ]; then
    echo "check_bruteforce.nofile::path==${log_file}__distib==${check_support_os} | failed_login=0;;;;"
    exit 3
fi

# Extract Failed password from log file
count=$(tac ${log_file} | gawk -v p="${period}" '
    BEGIN {
        m["Jan"]=1;m["Feb"]=2;m["Mar"]=3;m["Apr"]=4;  m["May"]=5;  m["Jun"]=6
        m["Jul"]=7;m["Aug"]=8;m["Sep"]=9;m["Oct"]=10; m["Nov"]=11; m["Dec"]=12
        count = 0;
        s=systime();
        current_year = strftime("%Y", s);
        current_month = strftime("%m", s);
    }
    /Failed password/{
            month = $1;   # Месяц
            day = $2;     # День
            t = $3;

            split(t, tp, ":");
            hour = tp[1];    # Часы
            minute = tp[2];  # Минуты
            second = tp[3];  # Секунды

            # If today is January and we get Dec lines in log then we should set the previous year
            if ( current_month == "01" && m[month] == 12 ) {
                year = current_year - 1
            } else {
                year = current_year
            }

	    # creating a string for mktime
	    ds = sprintf("%d %d %d %d %d %d", year, m[month], day, hour, minute, second);
            ts = mktime(ds)
            if ( s - ts < p ) {
                count++
            } else {
                next
            }
    }
    END {
        print count
    }
')

perfdata="failed_login=${count};;;;"

(( period = period / 60 ))

if [ $count -ge $crit ]; then
    output="failed_login==${count}__treshold==${crit}__time==${period}"
    state=2
elif [ $count -ge $warn ]; then
    output="failed_login==${count}__treshold==${warn}__time==${period}"
    state=1
else
    output="failed_login==${count}__treshold==${warn}__time==${period}"
    state=0
fi

echo "check_bruteforce.${states_text[$state]}::${output} | ${perfdata}"
exit $state
