#!/bin/bash
#
# Simple check show error password authorization
#
# Usage: check_beanstalk [-H] [-w] [-c] [-t]
#   -H --help       output this help
#   -w --warn       warning treshold messages in queue authorization
#   -c --crit       critical treshold messages in queue authorization
#   -t --time       time (min) to read log
#   -l --log        path to log authorization
#
# Default setting (warn=50, crit=70, time=5, log=/var/log/secure)
# WARNING: execution time increases from the specified time
# Copyleft TolkIT (team@tolkit.top)
# author Aleksey Maltsev (lexa.thinker@gmail.com)

# Default Settings
state=3
current_time=$(date +%s)
states_text=("ok" "warning" "critical" "unknown")
warn=${warn:=50}
crit=${crit:=70}
count_min=${t:=5}
log_file=${log_file:="/var/log/secure"}

declare -A OS
OS["centos"]="/var/log/secure"
OS["ubuntu"]="/var/log/auth.log"
OS["debian"]="/var/log/auth.log"
# Your OS could be here

# Search distribution name OS and add path to log
for name in ${!OS[@]}; do
    if [ "$( < /etc/os-release grep -w "ID" | grep -c "${name}")" -eq 1 ]; then
        log_file=${OS[$name]}
        check_support_os=$name
    else
        check_support_os=$( < /etc/os-release grep -w "ID" | awk '{print substr($0, 4, length($0)-1)}' | sed 's/"//g')
    fi
done

# Check add key
while [[ -n "$1" ]]; do
    case $1 in
        --warn | -w)
            warn=$2
            shift
            ;;
        --crit | -c)
            crit=$2
            shift
            ;;
        --time | -t)
            count_min=$2
            shift
            ;;
        --log | -l)
            log_file=$2
            shift
            ;;

        --help | -H)
            sed -n "2,15p" "$0" | tr -d '#'
            exit 3
            ;;
        *)
            echo "Unknown argument: $1"
            exit 3
            ;;
    esac
    shift
done

# Check exist file
if [ ! -e $log_file ]; then
    echo "check_bruteforce.nofile::path==${log_file}__distib==${check_support_os} | failed_login=0;;;;"
    exit 3
fi

# Extract Failed password from log file
START_TIME=$(date --date="${count_min} minutes ago" "+%b %_d %H:%M")
count=$(awk -v start_time="$START_TIME" '
    BEGIN { count = 0 }
    $0 ~ start_time, 0 {if ($0 ~ /Failed password/) count++ }
    END { print count }
' "$log_file")


echo $count

perfdata="failed_login=${count};;;;"

if [ $count -ge $crit ]; then
    output="failed_login==${count}__treshold==${crit}"
    state=2
elif [ $count -ge $warn ]; then
    output="failed_login==${count}__treshold==${warn}"
    state=1
else
    output="failed_login==${count}__treshold==${warn}"
    state=0
fi

echo "check_bruteforce.${states_text[$state]}::${output} | ${perfdata}"
exit $state
