#!/bin/bash

#Example
#./check_io_disk.sh sdc 20.0 28.0
#example output: check_disk_io_ok::disk==sda__await=0.8 | await=0.8;;;; read=0.35;;;; write=1.7;;;;

DISK=$1
WARN=$2
CRIT=$3

if [ "$(iostat -d "${DISK}" | wc -l)" -gt 5 ]; then     #fix for debian (newer version iostat 12)
  stat=$(iostat -d "${DISK}" -xmt 1 10 | tail -n +8 | sed -n '3~5 p')
  latency=$(echo "$stat" | awk '{print $10}' | tr "[:space:]" '+')
  rps=$(echo "$stat" | awk '{print $3}' | tr "[:space:]" '+')
  riops=$(echo "$stat" | awk '{print $2}' | tr "[:space:]" '+')
  wps=$(echo "$stat" | awk '{print $9}' | tr "[:space:]" '+')             #9
  wiops=$(echo "$stat" | awk '{print $8}' | tr "[:space:]" '+')
else
  stat=$(iostat -d "${DISK}" -xmt 1 10 | tail -n +7 | sed -n '3~4 p')
  latency=$(echo "$stat" | awk '{print $10}' | tr "[:space:]" '+')
  rps=$(echo "$stat" | awk '{print $6}' | tr "[:space:]" '+')
  riops=$(echo "$stat" | awk '{print $4}' | tr "[:space:]" '+')
  wps=$(echo "$stat" | awk '{print $7}' | tr "[:space:]" '+')
  wiops=$(echo "$stat" | awk '{print $5}' | tr "[:space:]" '+')
fi
L=$(echo "$latency" | sed 's/.$//' | bc -l | awk '{printf "%.2f", $0/9}')
R=$(echo "$rps" | sed 's/.$//' | bc -l | awk '{printf "%.2f", $0/9}')
W=$(echo "$wps" | sed 's/.$//' | bc -l | awk '{printf "%.2f", $0/9}')

if [ -z "$L" ]; then
        echo "check_disk_io_unknown::disk==${DISK}"
        exit 3
fi

if (( $(bc <<< "$L > $CRIT") )); then
        echo "check_disk_io_critical::disk==${DISK}__await==${L} | await=$L;;;; read=${R};;;; write=${W};;;;"
        exit 2
elif (( $(bc <<< "$L > $WARN") )); then
        echo "check_disk_io_warning::disk==${DISK}__await==${L} | await=$L;;;; read=${R};;;; write=${W};;;;"
        exit 1
fi
echo "check_disk_io_ok::disk==${DISK}__await==${L} | await=$L;;;; read=${R};;;; write=${W};;;;"
exit 0