#!/bin/bash

#example
#check_redis_doctor 
#example output: check_redis_doctor_ok::success==0__message=="Hi Sam, I can't find any memory issue in your instance. I can only account for what occurs on this base." | success=0

exit=0
success=0
message=$(redis-cli memory doctor)
echo "${message}" | grep -q "I can't find any memory issue" && success=0 || success=1 
if [ "${success}" -eq 0 ]; then
  echo "check_redis_doctor_ok::message=="${message}" | success=0"
  exit=0
else
  message=$(echo "${message}" | grep -w "^ * " | sed '/...//')
  echo "check_redis_doctor_warn::message=="${message}" | success=1"
  exit=1
fi
exit ${exit}