#!/bin/bash
#
# Simple check show Redis used memory info
#
# Usage: check_redis_memory [-H] [-w] [-c] [-f] [-b]
#   -H --help       output this help
#   -w --warn       warning treshold percent used memory percent
#   -c --crit       critical treshold percent used memory percent
#   -f --fwarn      warning treshold factor fragmentation memory
#   -b --block      block warning/error status if low memory use Redis. Use are percentages.
#
# Default setting (warn=85, crit=90, f_warn=1.25, block=10)
# Copyleft TolkIT (team@tolkit.top)
# Author Aleksey Maltsev (lexa.thinker@gmail.com)
state=3
states_text=("ok" "warning" "critical" "unknown")

warn=${warn:=85}
crit=${crit:=90}
f_warn=${f_warn:=1.25}
block=${block:=10}

# Check add key
while [[ -n "$1" ]]; do
    case $1 in
        --warn | -w) warn="$2";
           shift
           ;;
        --crit | -c) crit="$2";
           shift
           ;;
        --fwarn | -f) f_warn="$2";
           shift
           ;;
        --block | -b) block="$2";
           shift
           ;;
        --help | -H) sed -n "2,14p" "$0" | tr -d '#';
           exit 3
           ;;
        *) echo "Unknown argument: $1";
           exit 3
           ;;
    esac
    shift
done

#extract memory info
memory_info=$(redis-cli info memory)

# check memory info
if [[ -z ${memory_info} ]]; then
    echo "check_redis_memory.nodata::data==0"
    exit 3
fi

gawk -F: -v u_crit="$crit" -v u_warn="$warn" -v f_warn="$f_warn" -v block="$block" '
    BEGIN{
        b_to_Gb=(1024 * 1024 * 1024)
    }

    #extract info

    /used_memory:/ {
        used_memory = $2 / b_to_Gb
    }
    /mem_fragmentation_bytes:/ {
        mem_fragmentation_bytes = $2 / b_to_Gb
    }
    /maxmemory:/ {
        maxmemory = $2 / b_to_Gb
    }
    /used_memory_rss:/ {
        used_memory_rss = $2 / b_to_Gb
    }
    /used_memory_peak:/ {
        used_memory_peak = $2 / b_to_Gb
    }
    END {
        # calc used memory and fragmentation

        fragmentation = used_memory_rss / used_memory
        p_used_memory = used_memory * 100 / maxmemory
        p_used_memory_rss = used_memory_rss * 100 / maxmemory


        # create perfdata and output to monopus

        perfdata = sprintf("maxmemory=%0.2f;;;; " \
                         "used_memory=%0.2f;;;; " \
                         "used_memory_peak=%0.2f;;;; " \
                         "fragmentation=%0.2f;;;; " \
                         , maxmemory, used_memory, used_memory_peak, fragmentation)
        output = sprintf("maxmemory==%0.2f" \
                         "__p_used_memory==%0.1f" \
                         "__used_memory_peak==%0.2f" \
                         "__fragmentation==%0.2f" \
                         , maxmemory, p_used_memory, used_memory_peak, fragmentation)

        # check fragmentation and add output text
        if (fragmentation < 1) {
            f_code=2
            text_code="swap_crit"
            output = output"__frag_treshold==1"
        }
        else if (fragmentation > 1.5 && p_used_memory > block) {
            f_code=2
            text_code="frag_crit"
            output = output"__frag_treshold==1.5"
        }
        else if (fragmentation > f_warn && fragmentation < 1.5 && p_used_memory > block) {
            f_code=1
            text_code="frag_warn"
            output = output"__frag_treshold=="f_warn
        }
        else {
            f_code=0
            text_code="frag_ok"
            output = output"__frag_treshold=="f_warn
        }

        # check used memory and add output text
        if (p_used_memory > u_crit) {
            u_code=2
            text_code=text_code"_used_memory_crit"
            output = output"__treshold=="u_crit
        }
        else if (p_used_memory > u_warn) {
            u_code=1
            text_code=text_code"_used_memory_warn"
            output = output"__treshold=="u_warn
        }
        else {
            u_code=0
            text_code=text_code"_used_memory_ok"
            output = output"__treshold=="u_warn
        }

        #check code priority
        if (u_code > f_code) {
            code = u_code
        }
        else {
            code = f_code
        }

        printf ("check_redis_memory.%s::%s | %s\n",text_code, output, perfdata)
        exit code
    }
' <<< "$memory_info"
