#!/bin/bash
state=3

if [ "$1" = "-w" ] && [ "$2" -gt "0" ] && [ "$3" = "-c" ] && [ "$4" -gt "0" ]; then
  err=$(pvesh get nodes/"$(hostname)"/tasks | grep vzdump)
  tot_count=$(echo "$err" | grep -c UPID)
  ok_count=$(echo "$err" | grep -c OK)
  list_err=$(echo "$err" | grep -v OK | awk '{print $2}' | sort -u | tr '\n' ',') #add list err VMs
  joberr_count=$(echo "$err" | grep -c "job errors") 
  if [ "$joberr_count" -gt 0 ]; then                    #if job error - immediately exit
    echo "back_stat_cri::total==$joberr_count|total=$joberr_count;;;;"
    exit 2
  fi
  (( errors = tot_count - ok_count ))                   #all is not OK - errors!
  if [ "$errors" -ge "$4" ]; then                       #if crit level exceeded
    echo "back_stat_cri::total==$errors|total=$errors;;;;"
    state=2
  elif [ "$errors" -ge "$2" ]; then                     #else if warn level exceeded
    echo "back_stat_war::total==$errors|total=$errors"
    state=1
  else                                                  #else All OK
    echo "back_stat_ok::total==0|total=$errors"         
    state=0
  fi
  exit $state
else
  echo "check_proxmox_backup v1.1"
  echo ""
  echo "Usage:"
  echo "check_proxmox_backup -w <warnlevel> -c <critlevel>"
  echo ""
  echo "warnlevel and critlevel is quantity value without %"
  exit
fi