#!/bin/bash
#
# Simple check queue events in Bitrix
#
# Usage: check_mysql_queries [-H] [-t] [-e] [-u]
#   -H --help       output this help
#   -t --threshold  threshold of events that generates the error
#   -e --events     name event, by default 'ticket'
#   -u --user       database user under which name check number events not success
#
# Copyleft TolkIT (team@tolkit.top)
# author Sergey Egorushkin (SeroEgor@Gmail.com)

while [[ -n "$1" ]]; do
    case $1 in
        --treshold | -t)
            treshold=$2
            shift
            ;;
        --event | -e)
            event=$2
            shift
            ;;
        --user | -u)
            user=$2
            shift
            ;;
        --help | -H)
            sed -n '2,13p' "$0" | tr -d '#'
            exit 3
            ;;
        *)
            echo "Unknown argument: $1"
            exit 3
            ;;
    esac
    shift
done

user=${user:='bx_clusteruser'}                                          # user name in database
treshold=${treshold:=50}                                                # set threshold not success events
event=${event:='ticket'}                                                # name event
num=$(mysql -e "USE sitemanager; SELECT COUNT(*) FROM b_event WHERE success_exec = 'N' AND event_name like '${event}%'" | tail -n +2)   # 

if [ "$num" -gt "$treshold" ]; then                                     # if number not success events greather threshold, then critical
    output="events==${num}__treshold==${treshold}__namevent==${event}"
    perfdata="events=${num};;;;"
    flag="crit"
elif [ "$num" -gt 0 ]; then                                             # if greather 0, then warning
    output="events==${num}__treshold==${treshold}__namevent==${event}"
    perfdata="events=${num};;;;"
    flag="warn"
else                                                                    # else ok
    output="events==${num}__treshold==${treshold}__namevent==${event}"
    perfdata="events=${num};;;;"
    flag="ok"
fi
echo "check_event_bitrix_${flag}::${output} | ${perfdata}"              # give values to monopus
exit 0